<!DOCTYPE html>
<html lang="en">
<head>
  <title>Reseller Mantra</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <style type="text/css">
   li{
   margin: 0 0 3px 0;
   }
  </style>
</head>
<body>

<div class="jumbotron text-center">
  <h1>Reseller Mantra</h1>
      
     
</div>
  
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <p>&nbsp;</p>
<p>Please read these conditions carefully before using the Platform/Website. By using the Platform/Website, you signify your agreement to be bound by these conditions.</p>
<p>THIS DOCUMENT IS AN ELECTRONIC RECORD IN TERMS OF THE INFORMATION TECHNOLOGY ACT, 2000 AND RULES MADE THEREUNDER. THIS ELECTRONIC RECORD IS GENERATED BY A COMPUTER SYSTEM AND DOES NOT REQUIRE ANY PHYSICAL OR DIGITAL SIGNATURES. <strong><u>THESE TERMS OF USE WERE UPDATED ON OCTOBER 29, 2015</u></strong>. PLEASE CAREFULLY READ THESE TERMS OF USE. BY USING THIS PLATFORM YOU INDICATE YOUR UNDERSTANDING AND ACCEPTANCE OF THESE TERMS. IF YOU DO NOT AGREE TO THESE TERMS YOU MAY NOT USE THIS PLATFORM.</p>
<p>The domain name www.resellermantra.com / www.resellermantra.in (hereinafter referred to as "Platfomr/Website") is owned by Gold Opium Technologies with its corporate address office at 102 ,Khush Disha Avenue, Bairathi Nagar, Indore Pin 452001, India (hereinafter referred to as "Reseller Mantra").</p>
<p>Your use of the Website and services and tools are governed by the following terms and conditions (&nbsp;"Terms of Use"&nbsp;) as applicable to the Website including the applicable policies which are incorporated herein by way of reference. If You transact on the Website, You shall be subject to the policies that are applicable to the Website for such transaction. By mere use of the Website, You shall be contracting with Resellermantra&nbsp; and these terms and conditions including the policies constitute Your binding obligations, with Resellermantra.</p>
<p>For the purpose of these Terms of Use, wherever the context so requires&nbsp;"You"&nbsp;or&nbsp;"User"&nbsp;shall mean any natural or legal person who has agreed to become a buyer on the Website by providing Registration Data while registering on the Website as Registered User using the computer systems. Resellermantra allows the User to surf the Website or making purchases without registering on the Website. The term&nbsp;"We"&nbsp;,&nbsp;"Us"&nbsp;,&nbsp;"Our"&nbsp;shall mean Resellermantra.</p>
<p>When You use any of the services provided by Us through the Plarform/Website, including but not limited to, (e.g. Product Reviews, Seller,Reseller,Buyer, Reviews), You will be subject to the rules, guidelines, policies, terms, and conditions applicable to such service, and they shall be deemed to be incorporated into this Terms of Use and shall be considered as part and parcel of this Terms of Use. We reserve the right, at Our sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time without any prior written notice to You. It is Your responsibility to review these Terms of Use periodically for updates / changes. Your continued use of the Website following the posting of changes will mean that You accept and agree to the revisions. As long as You comply with these Terms of Use, We grant You a personal, non-exclusive, non-transferable, limited privilege to enter and use the Website.</p>
<p>ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.&nbsp;By impliedly or expressly accepting these Terms of Use, You also accept and agree to be bound by Resellermantra Policies ((including but not limited to Privacy Policy available at Privacy) as amended from time to time.</p>
<p>1&nbsp; INTRODUCTION :</p>
<p>Reseller Mantra Supply all associated sites and applications linked with the same (the &ldquo;Application&rdquo;) are operated by Gold Opium Technoligies This Platform is operated by the Company under the brand Reseller Mantra.. The Company, through its Application offers an [e-Commerce marketplace for dropshippers, selling products across fashion and lifestyle categories, and associated marketing, payment, order management, enquiry management tools and other incidental services to enable the transactions as available from time to time, on the Application (the &ldquo;Services&rdquo;).</p>
<p>These terms and conditions (the &ldquo;Terms of Service&rdquo;) shall apply to all users of the Application, including without limitation users who are browsers, wholesale vendors (the &ldquo;Vendors&rdquo;), resellers (the &ldquo;Resellers&rdquo;), merchants, or contributors of content (collectively, the &ldquo;Users&rdquo;). By visiting or accessing any part of the Application or utilising the Services, the Users agree to be bound by these terms and conditions, including any additional terms and conditions and policies referenced herein. If the Users do not accept any or all of the Terms of Service, they may not access the Application or use any of the Services.</p>
<p>&nbsp;</p>
<p>this Platform, including all information, tools and services available from this Platform to You, the User, conditioned upon Your acceptance of all terms, conditions, policies and notices stated here. The User&rsquo;s use of the Platform and related tools and services thereof, including but not limited to viewing information, acting on such information and the transactions that may be implemented through the Platform, is governed by and shall be subject to these terms and conditions (&ldquo;Merchants&rsquo; Agreement&rdquo;&nbsp;or Buyers&rsquo; Agreement or&nbsp;&ldquo;Terms of Service&rdquo;&nbsp;or&nbsp;&ldquo;Terms&rdquo;), the terms whereof are subject to change at any time, without prior notice to You. Any new features or tools which are added to the current Platform shall also be subject to the Terms of Service. To ensure that You are aware of the changes, please review this Merchants&rsquo; Agreement/Buyers&rsquo; Agreement&nbsp; and all the documents referred to hereunder periodically.</p>
<p>If You continue to browse through this Platform, You are agreeing to be bound by the Terms which along with the&nbsp;<a href="#/static/privacyPolicy.html">Privacy Policy</a>&nbsp;govern Your relationship with Us. You confirm that You have also read and have agreed and accepted to be bound by the terms and conditions incorporated in the terms of the Privacy Policy, which shall be deemed to be a part of this Merchants&rsquo;/Buyers&rsquo; Agreement .</p>
<p>In the event You are representing an incorporated entity, You hereby confirm that You have been expressly authorised by such entity to consent this Merchants&rsquo;/Buyers&rsquo; Agreement , and such entity agrees to be bound by the terms hereunder.</p>
<p>This Merchants&rsquo;/Buyers&rsquo; Agreement&nbsp; sets forth the legally binding terms of Your use of the Platform and related services. By proceeding further, You confirm that You have read and have agreed and accepted to be bound by the terms and conditions mentioned herein and incorporated in any additional guidelines or rules applicable to particular services on the Platform (&ldquo;Additional Documents&rdquo;), which shall be deemed to be a part of this Merchants&rsquo;/Buyers Agreement. In the event of any conflict between the terms of this Merchants&rsquo;/Buyers&rsquo; Agreement&nbsp; and any aforesaid Additional Documents, the Additional Documents shall prevail. If any of the terms of this Merchants&rsquo; Agreement or Buyers&rsquo; Agreement or of any of the Additional Documents are not acceptable to You, please do not use the Platform. Your continued usage of the Platform after any change constitutes Your acceptance of the amended Merchants&rsquo;/Buyers&rsquo; Agreement.</p>
<p>Your Account and Registration Obligations</p>
<p>If You use the Website/Platform, You shall be responsible for maintaining the confidentiality of your Display Name and Password and You shall be responsible for all activities that occur under your Display Name and Password. You agree that if You provide any information that is untrue, inaccurate, not current or incomplete or We have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with the this Terms of Use, We shall have the right to indefinitely suspend or terminate or block access on the Website/Platform and refuse to provide You with access to the Website/Platform.</p>
<p>Your mobile phone number and/or e-mail address is treated as Your primary identifier on the Website/Platform. It is your responsibility to ensure that Your mobile phone number and your email address is up to date on the Website/Platform at all times. You agree to notify Us promptly if your mobile phone number or e-mail address changes by updating the same on the Website/Platform through a onetime password verification.</p>
<p>You agree that ResellerMantra shall not be liable or responsible for the activities or consequences of use or misuse of any information that occurs under your display name in cases where You have failed to update Your revised mobile phone number and/or e-mail address on the Website/Platform.</p>
<p>&nbsp;</p>
<p>2 Eligibility</p>
<p>Persons who are &ldquo;incompetent to contract&rdquo; within the meaning of the Indian Contract Act, 1872 including minors, un-discharged insolvents etc. are not eligible to use the Application. Only individuals who are eighteen (18) years of age or older may use the Application and avail Services. The Company reserves the right to terminate the Users account and / or deny access to the Application if it is brought to the Company&rsquo;s notice that the Users are under the age of eighteen (18) years.</p>
<p>&nbsp;</p>
<ol start="3">
<li>SCOPE OF THE PLATFORM :</li>
</ol>
<p>The Platform is an e-portal/mobile based application for marketing, purchasing and selling of Products. By visiting our Platform and/ or listing some Product for marketing purposes, You engage in our&nbsp;&ldquo;Service&rdquo;&nbsp;and agree to be bound by the following terms and conditions (&ldquo;Terms of Service&rdquo;,&nbsp;&ldquo;Terms&rdquo;), including those additional terms and conditions and policies, as may be laid down under any Additional Documents as referenced herein and/or available by hyperlink. These Terms of Service apply to all Users of the Platform, including without limitation users who are browsers, vendors, customers, merchants, and/ or contributors of data, content, Information, pictorial representations and/or images (&ldquo;Content&rdquo;).</p>
<ol start="4">
<li>DISCLAIMERS OF WARRANTIES AND EXCLUSION OF LIABILITY :</li>
</ol>
<p>You are aware and fully understand that Platform is only a platform for prospective buyers and sellers and that:</p>
<ol>
<li>The Merchant&nbsp;shall alone have full legal and moral responsibility&nbsp;and liability for all the Products listed and sold on the Platform. The Company shall bear no liability or responsibility either for the Products being shown in catalogue or for the actual goods or services provided to the Buyers by You and all such liability, including financial and legal, shall solely lie with You;</li>
<li>The Merchant&nbsp;shall alone be responsible for procuring all licenses, permits, passes etc. as required by applicable law for each of the Products listed or sold through the Platform by You. The responsibility lies solely with You for ensuring that the Products being listed or sold are permitted for advertising, listing and sale under applicable laws;</li>
<li>It is Merchant&rsquo;s responsibility to&nbsp;not list or sell anything that is not permitted under applicable laws&nbsp;at the said point in time. An indicative list is provided below under clause 8, but that list is not exhaustive. We have the right but not the obligation to remove any item that is listed for sale from the Platform;</li>
<li>Platform is&nbsp;only facilitating payments on behalf of You&nbsp;and accepts no liability associated with the listing or delivery of goods or services by You</li>
<li>The Merchant shall make every effort to&nbsp;ensure that images of the Products exactly reflect the appearance of the Products in real life&nbsp;and the store display as accurately as possible the colors and images of the Products; and</li>
<li>The Merchant shall bear full liability and responsibility for dealing with any returns or refunds.&nbsp;The responsibility for communicating, managing and arranging for any refunds or returns lies entirely with You. The Company shall not be responsible for dealing with any returns or refunds.</li>
<li>The Company endeavours to make the Application available during the Company&rsquo;s working hours. However, the Company does not represent that access to the Application will be uninterrupted, timely, error free, free of viruses or other harmful components or that such defects will be corrected.</li>
<li>The Company does not warrant that the Application will be compatible with all hardware and software which is used by the Users. The Company shall not be liable for damage to, or viruses or other code that may affect, any equipment, software, data or other property as a result of downloading and installing the Application.</li>
<li>The Company does not represent or warranty that the information available on the Application will be correct, accurate or otherwise reliable.</li>
<li>The Vendors and Resellers shall be solely responsible about the details pertaining to specifics (such as quality, value, saleability, etc) of the products proposed to be sold or offered to be sold or purchased on the Application. The Company does not implicitly or explicitly support or endorse the sale or purchase of any products nor provide any warrantee/guarantee of the products sold to the Users, and in no event shall such products be the responsibility of the Company.</li>
<li>The Company is not responsible for any non-performance or breach of any contract entered into between the Vendors or Resellers and the Users. The Company cannot and does not guarantee that the concerned Users will perform any transaction concluded on the Application. The Company shall not and is not required to mediate or resolve any dispute or disagreement between the Users concerned.</li>
<li>The Company does not make any representation or warranty as to the item-specifics (such as legal title, creditworthiness, identity, etc) of any of its Users.</li>
<li>The Company does not at any point of time during any transaction between any Vendor or Reseller and a User take possession of any of the products offered nor does it at any point gain title to or have any rights or claims over such products. At no time shall the Company hold any right, title or interest over the products nor shall the Company have any obligations or liabilities in respect of such contract entered into between the Users. The Company is not responsible for damages or delays as a result of products which are out of stock, unavailable or back ordered.</li>
<li>The Company only provides a platform for communication and it is agreed that the contract for sale of any of the products shall be a strictly bipartite contract between the Users concerned.</li>
<li>The Application may be under constant upgrades, and some functions and features may not be fully operational.</li>
<li>The Application is provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis. The Company expressly disclaims all warranties of any kind, whether express or implied with respect to the records and other data that is made available by it to the Users.</li>
<li>The Company makes no representation or warranty that: (i) the Application will be accurate or reliable; (ii) the Application will be uninterrupted, timely, secure, or error-free; (iii) any information that may be obtained from the use of the Application will be accurate, timely or complete; or (iv) any errors in any software used on the site or in connection with the Application will be corrected.</li>
<li>The Company does not represent any of the users, and disclaims any liability with respect to any error or inconsistency with respect to any information relating to such users displayed on the site or with respect to the services provided. any information provided with respect to the users and fees payable is subject to change without notice. any trademark, word mark or intellectual property of any users belongs to such users alone, and the company has no right or claim over the same.</li>
<li>The Company is not responsible and will have no liability for: (i) any content or products provided by any persons or entities other than the Company; (ii) damages of any kind that result from the downloading of any data or any other materials on the site or through the Application; or (iii) the failures of the internet or any data or telecommunications equipment, system or network used in connection with the Application.</li>
<li>The Company shall not be liable for: any injury, loss, claim, or any direct, indirect, incidental, punitive, special, or consequential damages of any kind, including, without limitation any financial losses, loss of data, replacement costs, or any similar damages, whether based in contract, tort, strict liability or otherwise, arising from the use of the Application, or for any other claim related in any way to the use of the Application, including, but not limited to, any errors or omissions in any content, or any loss or damage of any kind incurred as a result of the use of the Application or any content posted, transmitted, or otherwise made available via the Application, even if advised of their possibility.</li>
<li>The Company shall not be liable to anyone else for any losses or injury arising out of or relating to the information provided on the Application. In no event will the Company or its employees, affiliates, authors or agents be liable to the Users or any third party for any decision made or action taken by the Users.</li>
</ol>
<p>&nbsp;</p>
<p>&nbsp;</p>
<ol start="5">
<li>Selling</li>
</ol>
<p>As a registered seller, you are allowed to list item(s) for sale on the Website in accordance with the Policies which are incorporated by way of reference in this Terms of Use. You must be legally able to sell the item(s) you list for sale on our Website. You must ensure that the listed items do not infringe upon the intellectual property, trade secret or other proprietary rights or rights of publicity or privacy rights of third parties. Listings may only include text descriptions, graphics and pictures that describe your item for sale. All listed items must be listed in an appropriate category on the Website. All listed items must be kept in stock for successful fulfilment of sales.</p>
<p>Resellers and Vendors are permitted to list products for sale on the Application in accordance with the Policies which are incorporated by way of reference in this Terms of Service. The Resellers and Vendors represent and warrant that they are legally able to sell or list the products on the Application; and the listed items do not infringe upon the intellectual property, trade secret or other proprietary rights or rights of publicity or privacy rights of third parties.</p>
<p>The listing description of the item must not be misleading and must describe actual condition of the product. If the item description does not match the actual condition of the item, you agree to refund any amounts that you may have received from the Buyer. You agree not to list a single product in multiple quantities across various categories on the Website. ResellerMantra reserves the right to delete such multiple listings of the same product listed by you in various categories.</p>
<p>&nbsp;</p>
<ol start="6">
<li>ONLINE STORE TERMS :</li>
<li>By agreeing to these Terms of Service, You represent that You are at least the age of majority in Your state or province of residence You and You have given Us, Your consent to allow any of Your minor dependents to use this Platform;</li>
<li>You may not, in the use of the Service, violate any laws in Your jurisdiction (including but not limited to copyright laws);</li>
<li>You must not transmit any worms or viruses or any code of a destructive nature;</li>
<li>That the Content submitted by You shall not be derogatory, offensive or misleading in any manner;</li>
<li>You are solely responsible for the Content that You upload, submit or send to or exchange on the Platform. We shall under no circumstances be responsible for any claims made by a third party in respect thereof;</li>
<li>Any fraudulent use of this Platform or applicable payment method to purchase the Products, which causes any monetary loss to the Company as a result of Your action/inaction shall be recovered from You. Without prejudice to the above, the Company reserves the right to initiate legal proceedings against You for the fraudulent use of this Platform or for any other unlawful act or omission in breach of this Merchants&rsquo; Agreement.</li>
<li>That images and pictorial representations on the Platform may be enhanced for advertising purposes;</li>
<li>That We will not be responsible for verifying any Content posted on the Platform;</li>
<li>That You also understand and acknowledge that the use of the Platform requires internet /mobile network connectivity. You shall bear the costs incurred to access and use the Platform and We shall not, under any circumstances whatsoever, be responsible or liable for such costs;</li>
<li>That You shall be solely responsible for all activities undertaken through Your User Account, whether or not You have authorized such activities or actions and shall, at all times, keep the Company indemnified in this regard;</li>
<li>That You shall be responsible for checking the Content, Product description and other related information; and</li>
<li>If You are registering as a business entity, You represent that You are duly authorized by the business entity to accept this Merchants&rsquo; Agreement and You have the authority to bind that business entity to this Merchants&rsquo; Agreement.</li>
<li>A breach or violation of any of the Terms will result in an immediate termination of Services and may result in reporting to the law enforcement agencies.</li>
<li>GENERAL CONDITIONS :</li>
<li>We reserve the right to refuse Service to anyone (without assigning any reason) at any time.</li>
<li>You understand that Your Content (not including credit card information), may be transferred unencrypted and involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices. Credit card information is always encrypted during transfer over networks.</li>
<li>You agree not to reproduce, duplicate, copy, sell, resell or exploit any portion of the Service, use of the Service, or access to the Service or any contact on the Platform through which the Service is provided, without express written permission by Us.</li>
</ol>
<p>The headings used in this Merchants&rsquo; Agreement are included for convenience only and will not limit or otherwise affect these Terms.</p>
<ol start="8">
<li>PROHIBITED USES :</li>
</ol>
<p>In furtherance to Clause 4 (c) above,&nbsp;You undertake and warrant that You&nbsp;will not list/buy the following Products on the Platform:</p>
<ol>
<li>Adult products and pornographic materials (including child pornography) in any form (print, audio/video, multimedia messages, images, photographs, etc.);</li>
<li>Alcohol;</li>
<li>Animals and wildlife products &ndash; examples include live animals, mounted specimens, and ivory;</li>
<li>Artifacts;</li>
<li>Counterfeit goods and services infringing the IP (as defined below);</li>
<li>Crude oil;</li>
<li>Electronic surveillance equipment prohibited by law;</li>
<li>Embargoed goods from prohibited countries;</li>
<li>Endangered species of animals and plants, whether alive or dead;</li>
<li>Event tickets which are exempted from resale by law;</li>
<li>Firearms, weapons, and knives &ndash; examples include pepper spray, replicas, and stun guns;</li>
<li>Any financial services;</li>
<li>Food and healthcare items without holding requisite permits;</li>
<li>Grey market products;</li>
<li>Government related items/ equipment (like wireless equipment with frequency used by the police, uniforms of Government officials including but not limited to the use by the police/ the Indian army, etc.)</li>
<li>Government issued documents like passports etc.;</li>
<li>Hazardous, restricted, or regulated materials &ndash; examples include batteries, fireworks, and refrigerants;</li>
<li>Human remains and body parts;</li>
<li>IP in any form (including but not limited to music, movies, books, designs) for which the Merchant do not hold the distribution rights;</li>
<li>Invoices and receipts (including blank and pre-filled);</li>
<li>Liquefied petroleum gas cylinder;</li>
<li>Lottery tickets;</li>
<li>Mailing lists and personal information;</li>
<li>Maps and literature where Indian external boundaries have been shown incorrectly;</li>
<li>Medicines, drugs and drug paraphernalia that require a registered medical practitioner&rsquo;s prescription;</li>
<li>Narcotic drugs and psychotropic substances as defined under the Narcotic Drugs and Psychotropic Substances Act, 1985;</li>
<li>Offensive material which is likely to offend the sentiments of people whether on the grounds of religion, race, caste, sex or place of birth, race, ethnicity, or culture;</li>
<li>Radioactive materials;</li>
<li>Reptile skins;</li>
<li>Sex determination Kit as under the Pre-Conception and Pre-Natal Diagnostic Techniques Act, 1994;</li>
<li>Stocks and securities;</li>
<li>Real estate;</li>
<li>Radioactive materials;</li>
<li>Stolen property;</li>
<li>Tobacco;</li>
<li>Any other sanctioned or prohibited items or services as per applicable laws; and</li>
<li>Any other item deemed unfit by Company.</li>
</ol>
<p>In addition to other prohibitions as set forth in the Terms of Service, You are prohibited from using the Platform or its Content:</p>
<ol>
<li>for any unlawful purpose;</li>
<li>to solicit others to perform or participate in any unlawful acts;</li>
<li>to violate any international, federal, provincial or state regulations, rules, laws, or any applicable ordinances;</li>
<li>to infringe upon or violate our intellectual property rights or the intellectual property rights of others;</li>
<li>to harass, abuse, insult, harm, defame, slander, disparage, intimidate, or discriminate based on gender, sexual orientation, religion, ethnicity, race, age, national origin, or disability;</li>
<li>to submit false or misleading information;</li>
<li>to upload or transmit viruses or any other type of malicious code that will or may be used in any way that will affect the functionality or operation of the Service or of any related Platform, other Platforms, or the internet;</li>
<li>to collect or track the personal information of others;</li>
<li>to spam, phish, pharm, pretext, spider, crawl, or scrape;</li>
<li>for any obscene or immoral purpose; or</li>
<li>to interfere with or circumvent the security features of the Service or any related Platform, other Platforms, or the internet. We reserve the right to terminate Your use of the Service or any related Platform for violating any of the prohibited uses.</li>
<li>TERMS OF USE :</li>
</ol>
<p>You acknowledge that certain parts of this Platform are available only if You register on this Platform by following the registration process mentioned under this Merchants&rsquo;/Buyers&rsquo; Agreement.</p>
<ol start="10">
<li>ACCURACY, COMPLETENESS AND TIMELINESS OF INFORMATION :</li>
<li>We are not responsible if information made available on the Platform is not accurate or not complete or not current. The material on the Platform is provided for general information only and should not be relied upon or used as the sole basis for making decisions without consulting primary and more accurate sources of information. Any reliance on the material on the Platform is at your own risk; and</li>
<li>We reserve the right to modify the contents of the Platform at any time, but We have no obligation to update any information on the Platform. You agree that it is Your responsibility to monitor changes to Our Platform.</li>
<li>MODIFICATIONS TO THE SERVICE AND PRICES :</li>
</ol>
<p>We reserve the right at any time to modify or discontinue the Service (or any part or content thereof) without notice at any time. We shall not be liable to You or to any third-party for any modification, price change, suspension or discontinuance of the Service.</p>
<ol start="12">
<li>PRICE OF THE PRODUCTS:</li>
<li>The Merchant undertakes and warrants that at all times, the sale price of Product provided by the Merchant for listing and display on the Platform shall be:</li>
<li>Inclusive of all taxes; and</li>
<li>the exact price at which the Product would be sold to the Buyer.</li>
</ol>
<p>We will in no way be responsible for assisting You in relation to any claims with respect to tax payable on the Products sold by You on the Platform.</p>
<p>You agree to indemnify, defend and hold harmless the Company and our parent, subsidiaries, affiliates, form any loss arising out of or in relation to any : (i) claims with respect to taxes to be paid on the Products sold by You on the Platform; and/or (ii) with respect to any misrepresentation of the sale price of the Products listed by You on the Platform.</p>
<ol start="13">
<li>PRODUCTS :</li>
</ol>
<p>We reserve the right, but not the obligation, to limit the sales of our Services to any person, geographic region or jurisdiction. We may exercise this right on a case-by-case basis. We reserve the right to limit the quantities of any Products that You offer. All descriptions of Products or Product pricing are subject to change at any time without notice, at our sole discretion. We reserve the right to discontinue any Product at any time. Any offer for any Product made on this Platform is void where prohibited.</p>
<p>We do not warrant that the quality of any Products, information, or other material purchased or obtained by any Buyers from You will meet the Buyers&rsquo; expectations, or that any errors in the Service will be corrected. You will be solely responsible for the same.</p>
<ol start="14">
<li>OPTIONAL TOOLS :</li>
</ol>
<p>We may provide You with access to third-party tools which We neither monitor nor have any control over nor do We provide any input. You acknowledge and agree that we provide access to such tools on an &ldquo;as is basis&rdquo; and &ldquo;as available&rdquo; without any warranties, representations or conditions of any kind and without any endorsement. We shall have no liability whatsoever arising from or relating to your use of optional third-party tools.</p>
<p>Any use by You of optional tools offered through the Platform is entirely at Your own risk and discretion and You should ensure that You are familiar with and approve of the terms on which tools are provided by the relevant third-party provider(s).</p>
<p>We may also, in the future, offer new services and/or features through the Platform (including, the release of new tools and resources). Such new features and/or services shall also be subject to these Terms of Service.</p>
<ol start="15">
<li>THIRD-PARTY LINKS :</li>
</ol>
<p>Certain content or products available via the Application may include materials from third-parties.</p>
<p>&nbsp;</p>
<p>Third-party links on the Application may direct you to third-party websites that are not affiliated with the Company. The Company is not responsible for examining or evaluating the content or accuracy and does not warrant and will not have any liability or responsibility for any third-party materials or websites, or for any other materials, products, or services of third-parties.</p>
<p>&nbsp;</p>
<p>The Company is not liable for any harm or damages related to the purchase or use of goods, services, resources, content, or any other transactions made in connection with any third-party websites. Please review carefully the third-party&rsquo;s policies and practices and make sure to understand them before engaging in any transactions. Complaints, claims, concerns, or questions regarding third-party products should be directed to the third-party.</p>
<ol start="16">
<li>USER COMMENTS, FEEDBACK AND OTHER SUBMISSIONS :</li>
</ol>
<p>If, at Our request, You send certain specific submissions (for example contest entries) or without a request from Us, You send creative ideas, suggestions, proposals, plans, or other materials, whether online, by email, by postal mail, or otherwise (collectively, &ldquo;Comments&rdquo;), You agree that We may, at any time, without restriction, edit, copy, publish, distribute, translate and otherwise use in any medium any comments that You forward to Us.</p>
<p>We are and shall be under no obligation to:</p>
<ol>
<li>maintain any Comments in confidence;</li>
<li>pay compensation for any Comments; or</li>
<li>respond to any Comments.</li>
</ol>
<p>We may, but have no obligation to, monitor, edit or remove Content that we determine in our sole discretion are unlawful, offensive, threatening, libelous, defamatory, pornographic, obscene or otherwise objectionable or violates any party&rsquo;s intellectual property or these Terms of Service.</p>
<p>You agree that your Comments will not violate any right of any third-party, including copyright, trademark, privacy, personality or other personal or proprietary right. You further agree that Your Comments will not contain libelous or otherwise unlawful, abusive or obscene material, or contain any computer virus or other malware that could in any way affect the operation of the Service or any related Platform. You may not use a false e-mail address, pretend to be someone other than Yourself, or otherwise mislead us or third-parties as to the origin of any Comments. You are solely responsible for any Comments You make and their accuracy. We take no responsibility and assume no liability for any Comments posted by You or any third-party.</p>
<ol start="17">
<li>PERSONAL INFORMATION :</li>
</ol>
<p>Your submission of personal information is governed by Our&nbsp;<a href="#/static/privacyPolicy.html">Privacy Policy</a>.</p>
<ol start="18">
<li>ERRORS, INACCURACIES AND OMISSIONS :</li>
</ol>
<p>Occasionally there may be information on the Platform or in the Service that contains typographical errors, inaccuracies or omissions that may relate to product descriptions, pricing, promotions, offers, product shipping charges, transit times and availability. We reserve the right to correct any errors, inaccuracies or omissions, and to change or update information or cancel orders if any information in the Service or on any related Platform is inaccurate at any time without prior notice We undertake no obligation to update, amend or clarify information in the Service or on any related Platform, including without limitation, pricing information, except as required by law. No specified update or refresh date applied in the Service or on any related Platform, should be taken to indicate that all information in the Service or on any related Platform has been modified or updated.</p>
<ol start="19">
<li>DISCLAIMER OF WARRANTIES; LIMITATION OF LIABILITY :</li>
</ol>
<p>We do not guarantee, represent or warrant that your use of our Service will be uninterrupted, timely, secure or error-free. We do not warrant that the results that may be obtained from the use of the service will be accurate or reliable.</p>
<p>You agree that from time to time we may remove the Service for indefinite periods of time or cancel the Service at any time, without notice to You.</p>
<p>You expressly agree that Your use of, or inability to use, the service is at Your sole risk. We are not responsible for ensuring that the sale price and other consideration to be received from the Buyer (&ldquo;Sale Price&rdquo;) for sale of Products listed on the Platform to the Buyers. Any Service provided to you by Us is without any representation, warranties or conditions of any kind, either express or implied, including all implied warranties or conditions of due receipt of Sale Price and non-infringement.</p>
<p>In no case shall the Company, Our directors, officers, employees, affiliates, agents, contractors, interns, suppliers, service providers or licensors be liable for any injury, loss, claim, or any direct, indirect, incidental, punitive, special, or consequential damages of any kind, including, without limitation lost profits, lost revenue, lost savings, loss of data, replacement costs, or any similar damages, whether based in contract, tort (including negligence), strict liability or otherwise, arising from Your use of any of the Service, or for any other claim related in any way to Your use of the Service, including, but not limited to, any errors or omissions in any content, or any loss or damage of any kind incurred as a result of the use of the Service or any Content (or product) posted, transmitted, or otherwise made available via the Service, even if advised of their possibility. In states or jurisdictions that do not allow the exclusion or the limitation of liability for consequential or incidental damages, in such states or jurisdictions, our liability shall be limited to the maximum extent permitted by law.</p>
<ol start="20">
<li>COPYRIGHT AND TRADEMARK :</li>
</ol>
<p>Each time You upload the Content, You grant the Company a worldwide non-exclusive, transferable, royalty free license to use any such content including by way of distribution, storage, hosting, sub-license, reproduction, communication, creation of derivative works, and modification of such content. You accept that such license will not terminate upon Your deletion or removal of the Content or other uploaded content in respect of which it is granted; and shall continue to be used by the Company, on the Platform.</p>
<p>You agree and confirm that:</p>
<ol>
<li>All copyright, database right and all other proprietary rights, title and interest in all Content and or information presented on this Platform (&ldquo;IP&rdquo;) is owned by and/or licensed to Us or owned by and/or licensed to the manufacturer of the Products and/or Services or is owned by and/or licensed to the person uploading such Content and is or may be protected or covered by copyright, trade mark, intellectual property law and/or other proprietary rights, unless expressly stated otherwise.</li>
<li>No extracts of this Platform or part thereof shall be displayed, printed or downloaded by You or with Your assistance, for any reason, including without limitation to commercialise any IP in any way.</li>
<li>Your use of this Platform does not confer on You or any other party, any licence or other rights under the intellectual property or other proprietary rights of the Company, the manufacturer of the Products and/ or Services and/or of any third party, whether implied or otherwise.</li>
<li>The Company shall not be held liable for any claims relating to infringement of any intellectual property rights in relation to the Products and/or Services their content and/or Content.</li>
<li>INDEMNIFICATION :</li>
</ol>
<p>You/User agree to indemnify, defend and hold harmless the Company and our parent, subsidiaries, affiliates, partners, officers, directors, agents, contractors, licensors, service providers, subcontractors, suppliers, interns and employees, harmless from any claim or demand, including reasonable attorneys&rsquo; fees, made by any third-party due to or arising out of Your breach of these Terms of Service or the documents they incorporate by reference, or Your violation of any law or the rights of a third-party.</p>
<ol start="22">
<li>SEVERABILITY :</li>
</ol>
<p>In the event that any provision of these Terms of Service is determined to be unlawful, void or unenforceable, such provision shall nonetheless be enforceable to the fullest extent permitted by applicable law, and the unenforceable portion shall be deemed to be severed from these Terms of Service, such determination shall not affect the validity and enforceability of any other remaining provisions.</p>
<ol start="23">
<li>TERMINATION :</li>
</ol>
<p>These Terms of Service are effective unless and until terminated by either You or Us. If in our sole judgment You fail, or we suspect that You have failed, to comply with any term or provision of these Terms of Service, we also may terminate this Merchants&rsquo; Agreement at any time without notice and You will remain liable for all amounts due up to and including the date of termination; and/or accordingly may deny You access to our Services (or any part thereof).</p>
<ol start="24">
<li>ENTIRE AGREEMENT :</li>
</ol>
<p>These Terms of Service and any policies or operating rules posted by Us on this Platform or in respect to The Service constitutes the entire agreement and understanding between You and Us and govern Your use of the Service, superseding any prior or contemporaneous agreements, communications and proposals, whether oral or written, between You and Us (including, but not limited to, any prior versions of the Terms of Service).</p>
<p>Our failure to exercise or enforce any right or provision of these Terms of Service shall not constitute a waiver of such right or provision.</p>
<p>Any ambiguities in the interpretation of these Terms of Service shall not be construed against the drafting party.</p>
<p><strong>Waiver</strong></p>
<p>The failure of the Company to exercise or enforce any right or provision of these Terms of Service shall not constitute a waiver of such right or provision.</p>
<ol start="25">
<li><strong>Governing law and dispute resolution</strong></li>
</ol>
<p>These Terms of Service are governed by the laws of India. Any action, suit, or other legal proceeding, which is commenced to resolve any matter arising under or relating to this Application, shall be subject to the jurisdiction of the courts at Indore,Madhya Prdesh, India.</p>
<p>&nbsp;</p>
<ol start="26">
<li>FORCE MAJEURE :</li>
</ol>
<p>We shall not be held liable for any of Our obligations under the Merchants&rsquo;/Buyers&rsquo; Agreement due to reasons beyond our control such as down time of servers, viruses, strikes, technical snags, system compatibility, natural calamities, acts of war, terror etc. You agree not to hold Us liable for any delay or adverse effect caused due to the occurrence of such an event.</p>
<ol start="27">
<li>CHANGES TO TERMS OF SERVICE :</li>
</ol>
<p>You can review the most current version of the Terms of Service at any time at this page. We reserve the right, at our sole discretion, to update, change or replace any part of these Terms of Service by posting updates and changes to our Platform. It is Your responsibility to check our Platform periodically for changes. Your continued use of or access to our Platform or the Service following the posting of any changes to these Terms of Service constitutes acceptance of those changes.</p>
<ol start="28">
<li><strong> Intellectual property</strong></li>
</ol>
<p>The Company is either the owner of intellectual property rights or have the non-exclusive, worldwide, perpetual, irrevocable, royalty free, sub-licensable (through multiple tiers) right to exercise the intellectual property, on the Application, and on the material published on it.</p>
<p>The Users must not modify the paper or digital copies of any materials printed or downloaded in any way, and they must not use any illustrations, photographs, video or audio sequences or any graphics separately from any accompanying text.</p>
<p>The Users must not use any part of the materials on the Application for commercial purposes without obtaining a licence to do so from the Company.</p>
<p>&nbsp;</p>
<ol start="29">
<li>CONTACT INFORMATION :</li>
</ol>
<p>Questions about the Terms of Service should be sent to Us at&nbsp;<a href="mailto:support@resellermantra.com">support@resellermantra.</a>in</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
			
    </div>
    
  </div>
  <!-- Footer -->
<footer class="page-footer font-small indigo">


    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2019 Copyright:
      <a href="http://resellermantra.in/"> resellermantra.in</a>
    </div>
    <!-- Copyright -->

  </footer>
  <!-- Footer -->
</div>

</body>
</html>
